<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\GerenciamentoDeOfertas.Communication\GerenciamentoDeOfertas.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\GerenciamentoDeOfertas.Exceptions\GerenciamentoDeOfertas.Exceptions.csproj" />
    <ProjectReference Include="..\GerenciamentoDeOfertas.Application\GerenciamentoDeOfertas.Application.csproj" />
  </ItemGroup>

</Project>
